#!/bin/bash
VERSION="1.1"

case "$1" in
  update)
    git add -A &&
    git commit -m "${2:-auto update}" &&
    git push
    ;;
  status)
    git status
    ;;
  log)
    git log --oneline -10
    ;;
  version)
    echo "gitr v$VERSION"
    ;;
  *)
    echo -e "Usage: gitr <command>\n\n  update [msg]   deploy current code (add + commit + push)\n  status         git status\n  log            last 10 commits\n  version        version info"
    ;;
esac
